// <auto-generated />
using BalanceEnquiry_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BalanceEnquiry_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230317144257_NewBalanceEnq")]
    partial class NewBalanceEnq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BalanceEnquiry_API.Models.Balance", b =>
                {
                    b.Property<string>("BookBalance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsableBalance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Balances");
                });
#pragma warning restore 612, 618
        }
    }
}
